FROM python:3.7
RUN apt-get update

WORKDIR /skynet

COPY ./requirements.txt /skynet/requirements.txt
RUN python -m pip install -r /skynet/requirements.txt

COPY . .
CMD ["/usr/local/bin/python", "/skynet/src/server.py"]